name: Checkmarx One Scan with SCA

on:
  push:
    branches:
      - main
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # ✅ ติดตั้ง dependencies ที่ต้องใช้
      - name: Install Maven, NPM, unzip, wget
        run: |
          sudo apt-get update
          sudo apt-get install -y maven npm wget unzip

      # ✅ ดาวน์โหลด SCA Resolver
      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz

      # ✅ ติดตั้ง Checkmarx One CLI
      - name: Install Checkmarx One CLI
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli

      # ✅ Run Scan (รวม SAST + SCA)
      - name: Run Checkmarx One CLI Scan (SAST + SCA)
        run: |
          /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
            scan create \
            -s . \
            --agent GitHub \
            --project-name fluk-test \
            --branch ${GITHUB_REF##*/} \
            --base-uri ${{ secrets.CX_BASE_URI }} \
            --tenant ${{ secrets.CX_TENANT }} \
            --client-id ${{ secrets.CX_CLIENT_ID }} \
            --client-secret ${{ secrets.CX_CLIENT_SECRET }} \
            --sca-resolver ./ScaResolver
